[ci]
runner = "codefloe-global"
provider = "crow"
platform = "forgejo"
runtime = "nix"
workspace = true
publish_crates = true

[ci.pages]
repo = "caniko/infernix"
canonical_domain = "infernix.tartanoglu.com"
