{
  imports = [
    ./brainrouter.nix
    ./comfyui.nix
    ./embr.nix
    ./fleet.nix
    ./hermes-agent.nix
    ./hermes-webui.nix
    ./gpu.nix
    ./load-balancer.nix
    ./manifest.nix
    ./mnemo.nix
    ./node.nix
    ./ollama.nix
    ./llama-swap.nix
    ./qdrant.nix
    ./surrealdb.nix
    ./visual-rubric.nix
  ];
}
